import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import vm from 'node:vm'
const source=await readFile(new URL('../../firmware/Chiller1/Ch1Ota.h',import.meta.url),'utf8')
const sketch=await readFile(new URL('../../firmware/Chiller1/Chiller1.ino',import.meta.url),'utf8')
function body(text,name){const m=new RegExp('(?:static )?(?:bool|void) '+name+'\\([^]*?\\) \\{').exec(text);assert(m,name);const start=m.index+m[0].length;let end=start,depth=1;for(;depth;end++){if(text[end]==='{')depth++;if(text[end]==='}')depth--}return text.slice(start,end-1)}
function translate(text){return text.replace(/OtaJob job;/g,'let job={};').replace(/OtaJob job=std::move\(otaPendingJob\);/g,'let job={...otaPendingJob};').replace(/std::move\(job\)/g,'({...job})').replace(/OtaJob\{\}/g,'({})').replace(/result\["o"\]\.is<JsonObject>\(\)/g,'(manifest !== null)').replace(/result\["o"\]\.as<JsonObject>\(\)/g,'manifest')}
const response=body(source,'ch1ProcessResponse'),tail=translate(response.slice(response.indexOf('OtaJob job;')))
const manifest=(id='one')=>({valid:true,job:{id,version:'v2',sha:'a'.repeat(64),url:'https://private.invalid/test',size:123,expires:1900000000}})
function harness(){const calls=[],alive=new Set();const c={otaPending:false,otaPendingJob:{},otaJobId:'',otaReady:true,otaSyncing:false,CH1_OTA_ENABLED:1,updating:false,manifest:manifest()};c.otaDecode=(m,j)=>{assert(alive.has('response JSON'));calls.push('decoded');if(!m.valid)return false;Object.assign(j,m.job);return true};c.otaRun=j=>{assert.equal(alive.size,0,'all telemetry and HTTP/TLS/JSON scopes must be gone');assert.equal(c.otaPending,false);calls.push('run:'+j.id);c.otaJobId=j.id};vm.createContext(c);for(const name of ['otaQueueDecodedJob','ch1OtaRunPending'])vm.runInContext(`function ${name}(${name==='otaQueueDecodedJob'?'job':''}){${translate(body(source,name))}}`,c);const sync=(updating=false)=>{alive.add('telemetry JSON');alive.add('HTTP');alive.add('TLS');calls.push('post');alive.delete('HTTP');alive.delete('TLS');calls.push('HTTP/TLS destroyed');alive.add('response JSON');c.updating=updating;try{return vm.runInContext(`(function(){${tail}})()`,c)}finally{alive.delete('response JSON');calls.push('response JSON destroyed');assert(!calls.some(x=>x.startsWith('run:')));alive.delete('telemetry JSON');calls.push('telemetry JSON destroyed');calls.push('sync returned')}};return {c,calls,alive,sync}}
test('CH1 manifest queues owned values while response/telemetry context lives',()=>{assert.doesNotMatch(response,/\botaRun\s*\(/);for(const name of ['ch1DeviceSync','ch1PostTelemetry','ch1Rpc'])assert.doesNotMatch(body(source,name),/\b(?:otaRun|ch1OtaRunPending)\s*\(/);assert.doesNotMatch(body(sketch,'pushTelemetry'),/\b(?:otaRun|ch1OtaRunPending)\s*\(/);const h=harness();h.sync();assert.equal(h.c.otaPending,true);h.c.manifest.job.url='destroyed';assert.equal(h.c.otaPendingJob.url,'https://private.invalid/test');assert(!h.calls.some(x=>x.startsWith('run:')));assert.match(source,/struct OtaJob \{ String id,version,sha,url;/)})
for(const name of ['setup','loop'])test(`CH1 ${name}: pending runner follows full telemetry return and consumes once`,()=>{assert.match(body(sketch,name),/pushTelemetry\(\);\s*ch1OtaRunPending\(\);/);const h=harness();h.sync();h.c.ch1OtaRunPending();h.c.ch1OtaRunPending();assert.equal(h.calls.filter(x=>x.startsWith('run:')).length,1);assert(h.calls.indexOf('telemetry JSON destroyed')<h.calls.indexOf('run:one'));assert(h.calls.indexOf('sync returned')<h.calls.indexOf('run:one'));h.alive.add('response JSON');vm.runInContext(`(function(){${tail}})()`,h.c);h.alive.clear();h.c.ch1OtaRunPending();assert.equal(h.calls.filter(x=>x.startsWith('run:')).length,1,'failed/current job must not replay')})
test('CH1 absent, invalid, updating, disabled and unavailable-persistence responses cannot queue',()=>{for(const mode of ['absent','invalid','updating','disabled','notready']){const h=harness();if(mode==='absent')h.c.manifest=null;if(mode==='invalid')h.c.manifest.valid=false;if(mode==='disabled')h.c.CH1_OTA_ENABLED=0;if(mode==='notready')h.c.otaReady=false;h.sync(mode==='updating');h.c.ch1OtaRunPending();assert.equal(h.c.otaPending,false);assert(!h.calls.some(x=>x.startsWith('run:')))}})
test('CH1 cannot replace pending job or consume while reporting',()=>{const h=harness();h.sync();h.c.otaQueueDecodedJob(manifest('other').job);assert.equal(h.c.otaPendingJob.id,'one');h.c.otaSyncing=true;h.c.ch1OtaRunPending();assert.equal(h.c.otaPending,true);h.c.otaSyncing=false;h.c.ch1OtaRunPending();assert.equal(h.c.otaPending,false);assert.equal(h.calls.filter(x=>x.startsWith('run:')).length,1)})
test('CH1 ordinary edge-free path has no extra sync and report-only sync cannot discover',()=>{assert.match(body(source,'ch1DeviceSync'),/if\(!updating \|\| otaSyncing/);assert.match(body(source,'ch1DeviceSync'),/ch1ProcessResponse\(response,true\)/);assert.doesNotMatch(body(sketch,'loop'),/ch1DeviceSync/);assert.equal((source.match(/otaRun\(job\);/g)||[]).length,1)})
