import test from 'node:test'
import assert from 'node:assert/strict'
import {inspectFirmware,uploadAndVerify,approveFirmware} from '../src/utils/ch1Firmware.js'
const make=()=>{const b=Buffer.alloc(1024);b[0]=0xe9;b.writeUInt16LE(9,12);b.writeUInt32LE(0xabcd5432,32);b.write('CH1OTA_DEVICE=ESP32-CH1\0CH1OTA_MODEL=CH1-ESP32S3-v1\0CH1OTA_VERSION=test\0',80);return new File([b],'app.bin')}
function fixture(file,{exists=false,stored=file}={}){const calls=[];const bucket={upload:async(p,f,o)=>{calls.push(['upload',o]);return {error:exists?{statusCode:'409'}:null}},download:async()=>{calls.push(['download']);return {data:stored}}};return {calls,bucket,client:{storage:{from:()=>bucket},rpc:async name=>{calls.push([name]);return {data:name==='ch1_firmware_status'?{releases:[]}:true}}}}}
test('upload verifies without publication; explicit approval re-downloads',async()=>{const f=make(),x=fixture(f);const v=await uploadAndVerify(x.client,f,'ESP32-CH1',await inspectFirmware(f,'ESP32-CH1'));assert.deepEqual(x.calls.map(c=>c[0]),['ch1_firmware_status','upload','download']);assert.equal(x.calls[1][1].upsert,false);await approveFirmware(x.client,f,'ESP32-CH1',v);assert.deepEqual(x.calls.slice(-2).map(c=>c[0]),['download','ch1_firmware_publish'])})
for(const mode of ['size','sha'])test(mode+' mismatch prevents verification',async()=>{const f=make(),b=Buffer.from(await f.arrayBuffer());b[700]=1;const x=fixture(f,{stored:new File([mode==='size'?b.subarray(1):b],'app.bin')});await assert.rejects(uploadAndVerify(x.client,f,'ESP32-CH1',await inspectFirmware(f,'ESP32-CH1')));assert.ok(!x.calls.some(c=>c[0]==='ch1_firmware_publish'))})
test('existing immutable object verifies without overwrite',async()=>{const f=make(),x=fixture(f,{exists:true});assert.ok(await uploadAndVerify(x.client,f,'ESP32-CH1',await inspectFirmware(f,'ESP32-CH1')));assert.equal(x.calls[1][1].upsert,false)})
test('approval requires verification and rejects changed selection',async()=>{const f=make(),x=fixture(f);await assert.rejects(approveFirmware(x.client,f,'ESP32-CH1',null));await assert.rejects(approveFirmware(x.client,f,'ESP32-CH1',{sha256:'stale'}));assert.equal(x.calls.length,0)})
test('approval rejects stored bytes changed after verification',async()=>{const f=make(),x=fixture(f),v=await uploadAndVerify(x.client,f,'ESP32-CH1',await inspectFirmware(f,'ESP32-CH1'));x.bucket.download=async()=>({data:new File(['corrupt'],'app.bin')});await assert.rejects(approveFirmware(x.client,f,'ESP32-CH1',v));assert.ok(!x.calls.some(c=>c[0]==='ch1_firmware_publish'))})
