create or replace view public.v_ch2_dashboard with (security_invoker=true) as
 WITH agg AS (
         SELECT max(ch2_latest.updated_at) AS latest_updated_at,
            max(ch2_latest.updated_at) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_HEARTBEAT'::text, 'CH3_HEARTBEAT'::text]))) AS heartbeat_updated_at,
            bool_or(ch2_latest.value_boolean) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_HEARTBEAT'::text, 'CH3_HEARTBEAT'::text]))) AS raw_heartbeat,
            bool_or(ch2_latest.value_boolean) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_SYSTEM_RUNNING'::text, 'CH3_SYSTEM_RUNNING'::text]))) AS system_running,
            bool_or(ch2_latest.value_boolean) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_COMP_1A_ENABLED'::text, 'CH3_COMP_1A_ENABLED'::text]))) AS comp_1a_enabled,
            bool_or(ch2_latest.value_boolean) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_COMP_1B_ENABLED'::text, 'CH3_COMP_1B_ENABLED'::text]))) AS comp_1b_enabled,
            bool_or(ch2_latest.value_boolean) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_COMP_1C_ENABLED'::text, 'CH3_COMP_1C_ENABLED'::text]))) AS comp_1c_enabled,
            bool_or(ch2_latest.value_boolean) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_COMP_2A_ENABLED'::text, 'CH3_COMP_2A_ENABLED'::text]))) AS comp_2a_enabled,
            bool_or(ch2_latest.value_boolean) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_COMP_2B_ENABLED'::text, 'CH3_COMP_2B_ENABLED'::text]))) AS comp_2b_enabled,
            bool_or(ch2_latest.value_boolean) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_COMP_2C_ENABLED'::text, 'CH3_COMP_2C_ENABLED'::text]))) AS comp_2c_enabled,
            max(ch2_latest.value_number) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_CHILLER_ENTERING_F'::text, 'CH3_CHILLER_ENTERING_F'::text]))) AS chiller_entering_f,
            max(ch2_latest.value_number) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_CHILLER_LEAVING_F'::text, 'CH3_CHILLER_LEAVING_F'::text]))) AS chiller_leaving_f,
            max(ch2_latest.value_number) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_FLOW_C1_GPM'::text, 'CH3_FLOW_C1_GPM'::text]))) AS flow_c1_gpm,
            max(ch2_latest.value_number) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_FLOW_C2_GPM'::text, 'CH3_FLOW_C2_GPM'::text]))) AS flow_c2_gpm,
            max(ch2_latest.value_number) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_CAPACITY_C1_TONS'::text, 'CH3_CAPACITY_C1_TONS'::text]))) AS capacity_c1_tons,
            max(ch2_latest.value_number) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_EVAP_OUT_C1_F'::text, 'CH3_EVAP_OUT_C1_F'::text]))) AS evap_out_c1_f,
            max(ch2_latest.value_number) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_EVAP_OUT_C2_F'::text, 'CH3_EVAP_OUT_C2_F'::text]))) AS evap_out_c2_f,
            max(ch2_latest.value_number) FILTER (WHERE (ch2_latest.point_code = ANY (ARRAY['CH2_PROCESS_DELTA_T_F'::text, 'CH3_PROCESS_DELTA_T_F'::text]))) AS process_delta_t_f
           FROM ch2_latest
        ), fresh AS (
         SELECT agg.latest_updated_at,
            agg.heartbeat_updated_at,
            agg.raw_heartbeat,
            agg.system_running,
            agg.comp_1a_enabled,
            agg.comp_1b_enabled,
            agg.comp_1c_enabled,
            agg.comp_2a_enabled,
            agg.comp_2b_enabled,
            agg.comp_2c_enabled,
            agg.chiller_entering_f,
            agg.chiller_leaving_f,
            agg.flow_c1_gpm,
            agg.flow_c2_gpm,
            agg.capacity_c1_tons,
            agg.evap_out_c1_f,
            agg.evap_out_c2_f,
            agg.process_delta_t_f,
            (COALESCE(agg.raw_heartbeat, false) AND (agg.latest_updated_at > (now() - '00:01:00'::interval))) AS fresh_heartbeat
           FROM agg
        )
 SELECT 'CH-NJ-02'::text AS asset_code,
    'ESP32-CH2-PLC'::text AS device_code,
    fresh_heartbeat AS is_online,
    fresh_heartbeat AS heartbeat,
    COALESCE(system_running, false) AS system_running,
    COALESCE(comp_1a_enabled, false) AS comp_1a_enabled,
    COALESCE(comp_1b_enabled, false) AS comp_1b_enabled,
    COALESCE(comp_1c_enabled, false) AS comp_1c_enabled,
    COALESCE(comp_2a_enabled, false) AS comp_2a_enabled,
    COALESCE(comp_2b_enabled, false) AS comp_2b_enabled,
    COALESCE(comp_2c_enabled, false) AS comp_2c_enabled,
    chiller_entering_f,
    chiller_leaving_f,
    flow_c1_gpm,
    flow_c2_gpm,
    capacity_c1_tons,
    evap_out_c1_f,
    evap_out_c2_f,
    process_delta_t_f,
    heartbeat_updated_at,
    latest_updated_at
   FROM fresh;
